# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170516_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='rating',
        ),
    ]
