# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_noun_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nounscore',
            old_name='noun',
            new_name='user',
        ),
    ]
