# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_noun_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='rating',
        ),
    ]
