# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_noun_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
