# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rapport_medals'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='virgin',
            field=models.BooleanField(default=False),
        ),
    ]
