# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
