# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='aud_vid',
            field=models.BooleanField(default=False),
        ),
    ]
